### ISSUE TITLE
Master: Simulation -> Execution - Goto instruction not showing up

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#102]
On the master branch ...
* default packet
* default profile
* default switch
* one configuration change to tables
    table0: 0|* -> goto 1;

Running the simulation several issues become apparent on the execution view.
* the instruction summary on selecting the default rule is not present
* this goto instruction is not in the instruction set
* the default properties of this context are not set
![screen shot 2015-02-01 at 10 06 56 am](https://cloud.githubusercontent.com/assets/971765/5992491/1d718930-a9fa-11e4-87dc-27b88c2e4f96.png)

What is strange ... is that the packet moves to the next table, as it should ... so this appears to be an issue with the view and not the core behavior. Also, if you look are the previous stage views (arrival), the properties are correctly set.
![screen shot 2015-02-01 at 10 08 50 am](https://cloud.githubusercontent.com/assets/971765/5992501/637655b4-a9fa-11e4-915c-1afbeff64ba6.png)

**Comment by sashajo** [comment]
Fixed in simulation-choice-ui branch with fix #103
