### ISSUE TITLE
Arrival viz: on 2nd packet arrival visualization steps through both packets

### ISSUE THREAD

**Issue by cchojnacki** [flowgrammable/flowsim#104]
When running a simulation that contains two packets, the arrival visualization of the 2nd packet is stepping through the first packet, then the second packet.

Steps to replicate:
1. setup default packet, profile, switch
2. Setup simulation to use two packets
3. Step through the simulation to arrival of the 2nd packet

![screen shot 2015-02-01 at 2 21 15 pm](https://cloud.githubusercontent.com/assets/491522/5993732/4ed01a80-aa1f-11e4-9bd1-a1c46fff7a6c.png)

**Comment by jassoncasey** [comment]
Fixed in branch: packet-arrival-fix
