### ISSUE TITLE
Packet : No method for specifying IPv4 TCP Payload Size/Contents

### ISSUE THREAD

**Issue by baykovr** [flowgrammable/flowsim#106]
Not possible to specify ipv4 payload size or contents, other than the default 0 byte payload.

**Comment by jassoncasey** [comment]
This capability is already present. 

Add a payload in the packet editor screen and set its byte count.

**Comment by jassoncasey** [comment]
Try this again ... let me know if the payload byte count is not working for you, or if it was just hard to find.

**Comment by baykovr** [comment]
Got it, didn't even realize you had to click on it.

Suggestion to change the cursor on hover over for that element to a hand.

**Comment by jassoncasey** [comment]
Yeah ... cursor change is a known issue #107.
