### ISSUE TITLE
Mouse over packet layer name

### ISSUE THREAD

**Issue by asutton** [flowgrammable/flowsim#107]
It's not immediately obvious from the shape of the mouse cursor that you can click on the name of a packet layer to expand it. It should switch to a hand or whatever the usual shape for buttons is.

Said otherwise, there needs to be a visual clue that leads a user to click on that name.

**Comment by jassoncasey** [comment]
This is an artifact of the bootstrap.ui angularjs library. We'll need to investigate how to actually turn this on, or change the underlying behavior. My guess is that its probably some default styling that the component is overriding.

**Comment by cchojnacki** [comment]
- Initial behavior: expand ethernet field editor view
- Mouse icon should change when hovering entire header

**Comment by sashajo** [comment]
Accordians changing open state when fields in packet editors were updated.
