### ISSUE TITLE
Simulation tabs should be in disabled state

### ISSUE THREAD

**Issue by cchojnacki** [flowgrammable/flowsim#125]
The tabs in the simulation screen should be disabled and unclickable by a user

![screen shot 2015-02-06 at 7 46 21 am](https://cloud.githubusercontent.com/assets/491522/6080209/49263d9a-add4-11e4-8d74-0806b2b75ed4.png)

**Comment by jassoncasey** [comment]
This appears to be an issue with grunt packaging up the release. It is not present in grunt serve, but is present in grunt release.
