### ISSUE TITLE
deleting packet/profile/switch from list only works if resource is loaded in fgcache

### ISSUE THREAD

**Issue by cchojnacki** [flowgrammable/flowsim#129]
The directive fglist is used to display available resources such as a list of packets, list of profiles, etc. Each item in the list is 'deletable' via the minus icon. Clicking the minus icon of a resource that has not been loaded into fgcache yet does not place the cache in a dirty state. The save icon does not become active.

Steps to reproduce:
1. Log in
2. Build multiple packets: packet1, packet2, packet3
3. Click Save
4. Logout
5. Login
6. Delete packet2

**Comment by jassoncasey** [comment]
Will the sequence always work, or does limited time between the last two steps make it likely to happen?

**Comment by cchojnacki** [comment]
Sequence will always work. Current implementation of fgcache is only able to delete resources which are loaded in the cache. I dont see the issue anymore with this fix. A more robust cache should be developed in a future release
