### ISSUE TITLE
Complex password reports "Invalid password"

### ISSUE THREAD

**Issue by sliqua** [flowgrammable/flowsim#130]
Should define a password requirements policy :-)

Attempted to use the following randomly generated 25 character password: 
2Y&'*_sy5]/nPwtWb)\EFm&ic

And was presented with "Invalid Password". I'm guessing it probably got hung up on the * or similar input.

![screen shot 2015-02-06 at 5 50 42 pm](https://cloud.githubusercontent.com/assets/23967/6088869/0a31a796-ae29-11e4-9dba-9f472cdd3cdf.png)

**Comment by sliqua** [comment]
Successfully registered using another 25 character password which contained upper/lower/numbers.

**Comment by jassoncasey** [comment]
There are two things here ...
* we don't every tell the user what our password policy is
* we should have a more permissive regex on acceptable passwords

**Comment by jassoncasey** [comment]
I can register with this password ... 
2Y&'*_sy5]/nPwtWb)\EFm&ic
But I can't login with the same password, I get an 'invalid password' error.

**Comment by sashajo** [comment]
can you verify again, I can't reproduce an issue

**Comment by jassoncasey** [comment]
Just verified on Hangout still doesn't work for me. Steps to reproduce ..
1. Register button
2. username: whatever, password: 2Y&'*_sy5]/nPwtWb)\EFm&ic
3. Submitt .... recieved an email, clicked on verificiation link, got to Verified Screen
4. Login button
5. username: <whatever>, password: 2Y&'*_sy5]/nPwtWb)\EFm&ic
6. Got 'Invalid Password' error on login attempt

![screen shot 2015-02-27 at 9 14 15 am](https://cloud.githubusercontent.com/assets/971765/6413828/17fda4f4-be61-11e4-81ed-504d738469ef.png)

This appears to be logic in the the screen itself validating user input before making a rest call.

**Comment by zcyisagoodboy** [comment]
why can't I register an flowsim account on the webpage you talked above?It always show an unknown error occur, I am almost crazy about this? If my password is invalid， it should inform me of that, so it's not a password problem?what's wrong with this?
