### ISSUE TITLE
Switch names cannot contain dashes or dots

### ISSUE THREAD

**Issue by sliqua** [flowgrammable/flowsim#132]
A lot of network folks like to name switches with specific detail about geographic location, datacenter PoP, or FQDNs such as:
er1.ams1
er1.ams1.nl.zip.zayo.com

Attempting to use a period or dash in the hostname results in:

![screen shot 2015-02-06 at 6 05 39 pm](https://cloud.githubusercontent.com/assets/23967/6089069/28d8e9c8-ae2b-11e4-9956-2939482deaee.png)

**Comment by jassoncasey** [comment]
Currently we only support names that follow the ANSI C identifier syntax [a-zA-Z_][a-zA-Z_0-9]*.

We need to increase the permissiveness of identifier regex. Would capturing valid domain names be enough, or would you want a wider valid name set?

**Comment by sliqua** [comment]
Using the example from above, I think you should be able to add a switch with just the subdomain portion (er1.ams1.nl.zip) or the entire FQDN (er1.ams1.nl.zip.zayo.com). But also have support for devices with dashes in the name, ie. (nvaiad-cor00.yellowfiber.net).   I don't think it's super critical, but for those trying to test using a "use case" of their existing network device names, it might throw people off :)

**Comment by cchojnacki** [comment]
Updated regex identifier to allow dashes and dots. Regex identifier is used for packets, profiles, switches, traces

**Comment by jassoncasey** [comment]
Using the name: er1.ams1.nl.zip.za-yo.com

Fails on: Profile, Switch, Simulation ... works for packet
