### ISSUE TITLE
Trace controller doesnt update on switch deletion

### ISSUE THREAD

**Issue by cchojnacki** [flowgrammable/flowsim#146]

**Comment by jassoncasey** [comment]
1. Create a packet, profile, switch, and trace
2. Delete the switch
3. Click on simulation ... switch is still there ...

**Comment by cchojnacki** [comment]
After deleting the switch did you save? Yes or no

**Comment by jassoncasey** [comment]
No save.

On Tue, Feb 10, 2015 at 10:54 AM, Colton Chojnacki <notifications@github.com

**Comment by cchojnacki** [comment]
In UI-state branch I have modified behavior to be the following:
* Deleting a packet or switch outside of the simulation view will result in the asset being removed from the trace
* Leaving the simulation screen will stop any simulation already in progress. This is a temporary fix to reduce erratic behavior with deleting switches, packets, etc. Ideally a user should be able to insert a flow during a simulation, but a user should not be able to delete the switch that is currently being used in the simulation. The simulation & switch config view need to be reworked so that a user can insert flow during simulation, but not be able to delete the switch
