### ISSUE TITLE
buffer exhaustion

### ISSUE THREAD

**Issue by cchojnacki** [flowgrammable/flowsim#147]

**Comment by jassoncasey** [comment]
1. Create a switch profile and set the buffer count to 1
2. Instantiate a switch from that profile
3. Create a trace with 2 packets
4. Watch the second packet throw an exception due to buffer exhaustion

**Comment by jassoncasey** [comment]
I believe the problem here is a basic resource leak. Buffers are allocated in arrival, I'm guessing they are not released in egress/groups.
