### ISSUE TITLE
Switch View / Tables tab /Flows Table on Load does not show content of flow tables

### ISSUE THREAD

**Issue by sashajo** [flowgrammable/flowsim#156]
Steps to reproduce:
Create Packet/ Profile / Switch
Add flow table in Tables section
Navigate away ( to simulation)
Select switch tab again.
By default first table is selected (blue ) but flow table looks empty.
User has to make selection for already selected table in order to see details.

Solution : Either remove initial selection or leave initial selection but show flow table content.

![image](https://cloud.githubusercontent.com/assets/3321760/6194570/9aef8af4-b393-11e4-8b98-20aded453063.png)

**Comment by cchojnacki** [comment]
fixed in ui-state branch
