### ISSUE TITLE
unsafe apply actions on dev.*

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#161]
It is possible to pop a VLAN and MPLS tag without proving the existence of those tags.

**Comment by jassoncasey** [comment]
I just checked the dev.* instance, and it still has this behavior. Was it fixed in develop, but not pushed?

**Comment by cchojnacki** [comment]
Fixed behavior to only display popTag action if a match for tag is present

**Comment by jassoncasey** [comment]
This bug is resolved; however, when I update the match set and I already have a action started ... the action dropdown isn't reset. This is nit picking but we should address in a later version.
