### ISSUE TITLE
bad behavior on page reload - live site

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#38]
The client is not saving the session key in browser storage. This results in some strange behavior if a use reloads the app while logged in. 

We need a bit more testing in this area. There was some strange packet list behavior that I can cannot recreate. ... more tests here please.

**Comment by jassoncasey** [comment]
Either session storage or local storage.

**Comment by baykovr** [comment]
Some testing,

Cookie remains in cache, however the sessions is gone.
Refreshing is essentially a full log-out with any unsaved changes lost. 

Chromium Version 40.0.2214.93 (64-bit)

**Comment by jassoncasey** [comment]
Logins are now persistent across reload.
