### ISSUE TITLE
can't delete default rule

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#49]
Created two flows:

1 | internal(in_port=1) -> eth(src=ff:ff:ff:ff:ff:ff), output(2);
0 | * -> output(2);

Ran the simulation ...
Tried to delete flow 0 | * ... failed

**Comment by jassoncasey** [comment]
This is still not fixed. I can't delete the 0 priority flow from the following configuration.
![screen shot 2015-01-22 at 9 46 03 pm](https://cloud.githubusercontent.com/assets/971765/5869025/5eb4aab6-a280-11e4-8bee-4a71a6af077c.png)

**Comment by cchojnacki** [comment]
Believe I found issue, please verify
