### ISSUE TITLE
green shadow not showing immediate output behavior

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#62]
Config
0|* -> apply: output(2), goto(1);

When entering into the execution stage stepping should be as follows:
1. execution the apply: output(2), move a green shadow (copy) from execution to out of the pipeline
    - currently the green shadow copy does not work
2. execute the goto instruction and update the table property id

**Comment by cchojnacki** [comment]
Fixed in simulation-packetBranch-ui, please verify

**Comment by jassoncasey** [comment]
This issue is resolved for executing apply: output(X). However, no animation of the green box is happening in the egress stage during execution of output(Y).

**Comment by jassoncasey** [comment]
Also, make sure you merge from master and ensure a clean jshint bill of health before you commit/push on this (or any branch).
