### ISSUE TITLE
execution view - instruction tooltip content is off

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#63]
The contents of the instruction set - instruction tooltip should be the full instruction action. While the instruction label is just the instruction name. There just wasn't enough real estate to show everything.

Examples
Goto - goto(3)
Meter - meter(5)
Metadata - metadata(value=0xff00ff00ff0f, mask=ff:ff:ff:ff:00:00:00)

**Comment by jassoncasey** [comment]
The tooltips are not quite write. They should look like the following ....
Label         Tooltip
===============
Goto           goto(3)
Meter          meter(5)
Metadata     metadata(value=0x0f0af0sdsdf, mask=0xasd)

Right now the tooltips are showing a value summary.

**Comment by jassoncasey** [comment]
Ok .... on reviewing this again the instruction tooltips are working, its the action list/set tooltips are not right.

**Comment by cchojnacki** [comment]
fixed in master, please verify

**Comment by jassoncasey** [comment]
This looks fixed.

We may want to consider whether to unify the tool tip display string format between actions and instructions.

What are your thoughts?
