### ISSUE TITLE
meter id not being updated

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#66]
When I have a meter instruction on a flow that matches the corresponding meter id is not being updated in the execution view.

**Comment by jassoncasey** [comment]
![screen shot 2015-01-23 at 4 20 34 pm](https://cloud.githubusercontent.com/assets/971765/5882913/ca6cbce4-a31b-11e4-936e-84dcda378e54.png)
![screen shot 2015-01-23 at 4 20 24 pm](https://cloud.githubusercontent.com/assets/971765/5882914/ca7622c0-a31b-11e4-8cd7-b86bc7f82127.png)
![screen shot 2015-01-23 at 4 20 05 pm](https://cloud.githubusercontent.com/assets/971765/5882916/ca76e318-a31b-11e4-8e0e-83575a53aaa7.png)
![screen shot 2015-01-23 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/971765/5882917/ca78653a-a31b-11e4-8884-4956e9c49d51.png)
![screen shot 2015-01-23 at 4 19 42 pm](https://cloud.githubusercontent.com/assets/971765/5882915/ca76ef7a-a31b-11e4-9e65-9591427f15f1.png)

**Comment by cchojnacki** [comment]
Following the above config I am unable to replicate the issue. Will need to discuss

**Comment by jassoncasey** [comment]
This appears to be resolved in master, but exists within extraction.
