### ISSUE TITLE
metadata halts execution

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#67]
When I attach a metadata instruction to a flow, it halts the simulation during the execution stage. It looks like the system can't really execute the metadata instruction.

**Comment by cchojnacki** [comment]
Currently attaching a metadata instruction which contains an empty value and mask field will generate an error during the execution phase.  

Question about this instruction...
1) If the user attaches a metadata instruction, but does not alter the value or mask field, what should the default value of the metadata value and mask field be?

**Comment by jassoncasey** [comment]
We need to rework the UI so that they can't enter an invalid meta data pair. I will add a separate ticket for that issue. We need to do this activity generically for all simple instructions: goto, meter, metadata. Simple being they're not a list of things.

**Comment by cchojnacki** [comment]
related to https://github.com/flowgrammable/flowsim/issues/89
