### ISSUE TITLE
Execution View instruction set summaries are not correct

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#68]
The instruction set summary in the top left part of the execution view is not showing the appropriate instruction short names. The short names are listed in flowsim-ui/design/execution.png. But for example:
Current      Correct
===============
me                    m
ap                     a
cl                      c
wr                     w
me                    md
go                     g

![screen shot 2015-01-23 at 7 09 48 am](https://cloud.githubusercontent.com/assets/971765/5874393/da2a11ce-a2ce-11e4-8a78-ff6c9b89f619.png)

**Comment by cchojnacki** [comment]
fixed on master
