### ISSUE TITLE
Missing context border in packet arrival view

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#70]
Location: Simulation -> Arrival

If you look at the context on the right side of the screen you will notice the grey border is missing from the top of the structure.
![screen shot 2015-01-23 at 7 21 01 am](https://cloud.githubusercontent.com/assets/971765/5874503/69204744-a2d0-11e4-8d65-5f36a36e2e45.png)

Is it possible to have this grey border extend slightly over the top of the context structure as in the design?
![arrival](https://cloud.githubusercontent.com/assets/971765/5874514/c1576384-a2d0-11e4-8f7b-640d0f6a335f.png)

**Comment by sashajo** [comment]
Fixed in extraction branch
