### ISSUE TITLE
Prevent a simulation from executing if there are no packets in the input trace

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#71]
Location: Simulation

Right now the simulation will happily start even if you dont have a packet in the packet trace sequence. We need to add an enabled property to the play button for this page. It should be linked to the the length of the input trace being > 0.
![screen shot 2015-01-23 at 7 31 43 am](https://cloud.githubusercontent.com/assets/971765/5874623/eaedfd92-a2d1-11e4-8397-11e65e132c5a.png)

**Comment by cchojnacki** [comment]
fixed on master

**Comment by jassoncasey** [comment]
This fix works; however, I noticed another condition we need to guard the 'play' button with. 

Every packet that is added to the packet trace must at least specify a in_port value. It should not be allowable to start a simulation if any packet in the trace does not have an in_port value set.
