### ISSUE TITLE
goto instruction should disappear as it executes

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#72]
Location: Simulation -> Execution

The goto instruction is properly updating the table property as it executes. However, it should also simultaneously disappear. It is not currently doing this.

Before
![screen shot 2015-01-23 at 7 35 00 am](https://cloud.githubusercontent.com/assets/971765/5874660/60315b6c-a2d2-11e4-938c-366f81e5e99a.png)

After
![screen shot 2015-01-23 at 7 35 24 am](https://cloud.githubusercontent.com/assets/971765/5874663/6ab8987a-a2d2-11e4-98b3-0867de169b2e.png)

**Comment by cchojnacki** [comment]
I haven't been able to reproduce this bug
