### ISSUE TITLE
Simulation arrival animation does not happen on a restart

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#73]
Location: Simulation -> Arrival

The first time you run a simulation the arrival stage presents the current packet buffer, and then buy clicking on step forward a packet arrival animation plays.

View after 'first play'
![screen shot 2015-01-23 at 7 39 00 am](https://cloud.githubusercontent.com/assets/971765/5874731/009b952c-a2d3-11e4-9c81-04cdfa655781.png)

However, if you click: stop, play, step ... the packet arrival animation does play. The final resulting view just appears.

View after stopping an animation and hitting 'play' again
![screen shot 2015-01-23 at 7 39 14 am](https://cloud.githubusercontent.com/assets/971765/5874736/0ede4df0-a2d3-11e4-95fa-64df8d886df9.png)

You can stop the simulation at any stage, hit play again, and repeat the same odd behavior.

If you stop the simulation and then click on a different page (packet, profile, switch), then click back to simulation and hit 'play' .. the arrival animation works as expected.

**Comment by sashajo** [comment]
Fixed in extraction branch.

**Comment by jassoncasey** [comment]
So the animation bug seems to be fixed. But there are some other issues that seem to be introduced in this branch. The instructions are not being displaying in the instruction set.

Switch->Table(0) Configuration
![screen shot 2015-01-25 at 8 44 15 am](https://cloud.githubusercontent.com/assets/971765/5891625/7fa202c4-a46e-11e4-9db9-5b2cc5dc869a.png)

Switch->Table(1) Configuration
![screen shot 2015-01-25 at 8 44 25 am](https://cloud.githubusercontent.com/assets/971765/5891626/877be28a-a46e-11e4-94c9-9a314bbfdfbc.png)

Simulation->Execution View (on entry)
![screen shot 2015-01-25 at 8 44 42 am](https://cloud.githubusercontent.com/assets/971765/5891627/9535ba0e-a46e-11e4-9f9c-d60e15296cce.png)

The packet and profile are just default instances, no special configuration.

I tested this in the master branch without issue. There is something in the extraction branch that causes this issue.

One quick point to note when you are working in the branch, make sure you rebase with master before you test your changes. Assuming you are on the extraction branch you can do this by:
git merge master

It is possible this will introduce a merge conflict. These are easy to solve, its just a diff of theirs/yours, edit out what you dont want including the <<<<, ====, >>>>. You will then have to add the file of the merge conflict using: git add <filename>. You can check the status of a merge (conflict free, issues, etc.) with: git status.
