### ISSUE TITLE
Switch -> Table -> Flow -> Instruction Validation issue

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#89]
For simple instructions, or instructions that are not write|apply, we need to have a better mechanism for input validation from the user. 

For example
* we should have a view of the active value
* we should have an input box or pair for the user to set a new value
* we should have a button that will take the input and make it active/set
* the button shouldn't be action, the input box should indicate error, when the input is not valid ... basically the same thing we do with general input boxes

**Comment by cchojnacki** [comment]
Couple questions

1) should criteria for valid values be based on switch profile?For instance a goto value is valid if it falls in a range specified by goto profile

2) should criteria for valid value be based on current table? For instance the instruction goto(5) in a flow on table 10 should be invalid (can't go backwards)

3) should there be a default active value?

**Comment by jassoncasey** [comment]
1. Yes, a goto value is only valid if it falls within the capabilities range for that table.

2. Again, correct. Validity is: Table X: goto(Y) | Y > X;

3. No, there should not be a default active value.

**Comment by jassoncasey** [comment]
Looks great. Merge and kill branch.
