### ISSUE TITLE
Simulation: green packet shadow not behavior properly on multiple packets

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#96]
In the simulation screen, when you have two or more packets configured in the the trace, the green packet shadow is behaving improperly.

1. Configure 2 packets on the simulation setup screen to inject into the switch
2. When processing is finishing on packet 1
    * disappear if packet is dropped/discarded
    * fly off the screen to the right if output
    * in either case there should be no green shadow on the pipeline at this point
3. Process the second packet of the simulation
    * packet flies in from the left into the arrival stage

**Comment by jassoncasey** [comment]
So the packet finishing processing is handled correctly, and the packet disappears. However, when processing the second packet the green shadow will travel backwards from egress to arrival, it should just fly in from the left.

**Comment by cchojnacki** [comment]
fixed
